dataloader:
  batch_size: 6                                         # training batch size, 12 for pre-train, 6 for cpc exp
  eval_batch_size: 12
  active_batch_size: 12

preprocessor:
  input_channel: 0
  target_channel: 1
  
  # feat_type: complx, linear, phase, mel, mfcc
  baseline:
    feat_type: mel
    log: True
    delta: 2
    cmvn: False

runner:
  learning_rate: 4.0e-5                                 # Learning rate for opt: ['4e-3' for fine-tune, '4e-3' for regualr downstream task training]
  warmup_proportion: 0.07                               # Proportion of training to perform linear rate warmup.
  gradient_clipping: 1.0                                # Maximum gradient norm
  total_step: 20000                                            # total steps for training, a step is a batch of update
  log_step: 500                                          # log training status every this amount of training steps
  eval_step: 1000                                         # evaluate every this amount of training steps
  save_step: 2000                                         # evaluate every this amount of training steps
  media_step: 4000
  sampler_refresh_step: 50
  sampler_collect_step: 25
  sampler_sample_num: 10
  active_refresh_step: 10
  active_query_num: 32
  active_buffer_weights: [1, 0, 0, 0]
  max_keep: 20                                           # maximum number of model ckpt to keep during training
  eval_splits: ['subtrain', 'dev', 'query_dev', 'test']
  eval_metrics: ['stoi', 'pesq_nb', 'sisdr']

objective:
  L1:
    {}
  SISDR:
    {}
  WSD:
    db_interval: 50
    alpha: 0.3

model:
  Linear:
    activation: ReLU
  LinearResidual:
    cmvn: True
  LSTM:
    hidden_size: 256
    num_layers: 3
    bidirectional: True
  Residual:
    hidden_size: 256
    num_layers: 3
    bidirectional: False
    activation: Sigmoid
    cmvn: True


OnlineDataset_train:
  speech:
    filestrs: '../datasets/speech_data/clean_trainset_wav_16k'
    sample_num: 1000
    select_sampled: False
  noise:
    filestrs: '../datasets/DNS-Challenge/datasets/noise'

  sample_rate: 16000
  max_time: 10000
  target_level: -25
  snrs: [-8, -6, -4, -2, 0, 2, 4, 6, 8]
  infinite: True
  pseudo_modes: [0]


OnlineDataset_test:
  speech:
    filestrs: '../datasets/speech_data/clean_testset_wav_16k/p232*'
    sample_num: 10
    select_sampled: False
  noise:
    filestrs: '../datasets/noise_data/Nonspeech/bell'

  sample_rate: 16000
  max_time: 10000
  target_level: -25
  snrs: [-8, -6, -4, -2, 0, 2, 4, 6, 8]
  half_noise: end
